version: '3.8'
services:
  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080"
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    hostname: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data:
