"""Change Group slug column validation

Revision ID: 25184c2b0e88
Revises: c8953f9f6296
Create Date: 2024-03-17 18:36:40.363996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25184c2b0e88'
down_revision: Union[str, None] = 'c8953f9f6296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
