"""Modify comment model

Revision ID: 6da657838200
Revises: 25184c2b0e88
Create Date: 2024-03-30 15:19:15.386437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da657838200'
down_revision: Union[str, None] = '25184c2b0e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('related_post', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('related_post', type_='foreignkey')

    # ### end Alembic commands ###
